"""
agbridge.protocol — Protocol event type definitions

All message types exchanged between server and client are defined here.
Register new events in this file.
"""


# ── Server → Client (Downstream Push) ────────────────────────

SYNC_FULL_STATE = "SYNC_FULL_STATE"

# System events
SYS_IDE_CONNECTED = "SYS_IDE_CONNECTED"
SYS_IDE_DISCONNECTED = "SYS_IDE_DISCONNECTED"

# File system deltas
FS_OP_CREATED = "FS_OP_CREATED"
FS_OP_DELETED = "FS_OP_DELETED"
FS_OP_MODIFIED = "FS_OP_MODIFIED"

# Git source control
GIT_STATUS_UPDATE = "GIT_STATUS_UPDATE"

# UI scraping deltas
UI_AGENT_UPDATE = "UI_AGENT_UPDATE"
UI_EDIT_ACTIONS_UPDATE = "UI_EDIT_ACTIONS_UPDATE"
UI_SETTINGS_UPDATE = "UI_SETTINGS_UPDATE"
UI_ACTIVE_EDITOR_UPDATE = "UI_ACTIVE_EDITOR_UPDATE"
UI_MODELS_UPDATE = "UI_MODELS_UPDATE"
UI_CONFIRM_UNDO_DIALOG = "UI_CONFIRM_UNDO_DIALOG"
UI_CONV_STATE_CHANGE = "UI_CONV_STATE_CHANGE"
UI_CONV_SCAN_STATE = "UI_CONV_SCAN_STATE"


# ── Client → Server (Upstream Command) ───────────────────────

CMD_INJECT_PROMPT = "CMD_INJECT_PROMPT"
CMD_FILE_READ = "CMD_FILE_READ"

# Workspace control
CMD_WORKSPACE_CREATE = "CMD_WORKSPACE_CREATE"
CMD_WORKSPACE_DELETE = "CMD_WORKSPACE_DELETE"

# IDE lifecycle control
CMD_IDE_OPEN = "CMD_IDE_OPEN"
CMD_IDE_CLOSE = "CMD_IDE_CLOSE"

# Agent edit actions
CMD_ACCEPT_ALL = "CMD_ACCEPT_ALL"
CMD_REJECT_ALL = "CMD_REJECT_ALL"

# Agent control
CMD_CANCEL = "CMD_CANCEL"
CMD_SELECT_MODEL = "CMD_SELECT_MODEL"
CMD_SELECT_MODE = "CMD_SELECT_MODE"
CMD_NEW_CONVERSATION = "CMD_NEW_CONVERSATION"
CMD_RETRY = "CMD_RETRY"
CMD_DISMISS_ERROR = "CMD_DISMISS_ERROR"
CMD_PRESS_DENY = "CMD_PRESS_DENY"
CMD_PRESS_ALLOW = "CMD_PRESS_ALLOW"
CMD_PRESS_ALLOW_WORKSPACE = "CMD_PRESS_ALLOW_WORKSPACE"
CMD_PRESS_ALLOW_GLOBALLY = "CMD_PRESS_ALLOW_GLOBALLY"
CMD_PRESS_RUN_SANDBOX = "CMD_PRESS_RUN_SANDBOX"
CMD_LIST_MODELS = "CMD_LIST_MODELS"
CMD_LIST_MODES = "CMD_LIST_MODES"
CMD_REFRESH_MODELS = "CMD_REFRESH_MODELS"
CMD_LIST_WORKFLOWS = "CMD_LIST_WORKFLOWS"
CMD_LIST_CONVERSATIONS = "CMD_LIST_CONVERSATIONS"
CMD_SELECT_CONVERSATION = "CMD_SELECT_CONVERSATION"
CMD_DELETE_CONVERSATION = "CMD_DELETE_CONVERSATION"
CMD_EXPAND_CONVERSATIONS = "CMD_EXPAND_CONVERSATIONS"
CMD_CLOSE_CONVERSATION_PANEL = "CMD_CLOSE_CONVERSATION_PANEL"

# Conversation scroll synchronization
CMD_SCROLL_CONVERSATION = "CMD_SCROLL_CONVERSATION"
CMD_CLEAR_CACHE = "CMD_CLEAR_CACHE"

# Undo / Rollback
CMD_UNDO_TO_PROMPT = "CMD_UNDO_TO_PROMPT"
CMD_CONFIRM_UNDO = "CMD_CONFIRM_UNDO"
CMD_CANCEL_UNDO = "CMD_CANCEL_UNDO"

# Prompt history
CMD_GET_LAST_PROMPT = "CMD_GET_LAST_PROMPT"

# Git commands
CMD_GIT_OP = "CMD_GIT_OP"

# ── Workspace lifecycle ──────────────────────────────────

SYS_WORKSPACE_REGISTERED = "SYS_WORKSPACE_REGISTERED"
SYS_WORKSPACE_UNREGISTERED = "SYS_WORKSPACE_UNREGISTERED"


# ── Heartbeat ────────────────────────────────────────────

SYS_PING = "PING"
SYS_PONG = "PONG"
